# Generated by Django 5.2 on 2025-04-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TVnerd.user'),
        ),
    ]
