# Generated by Django 5.1.7 on 2025-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0006_alter_watchlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
