# Generated by Django 5.2 on 2025-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0007_movie_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
