# Generated by Django 5.2 on 2025-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0008_remove_movie_is_featured_remove_watchlist_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='item_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
