# Generated by Django 5.1.7 on 2025-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('overview', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
