# Generated by Django 5.1.7 on 2025-04-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
