# Generated by Django 5.1.7 on 2025-05-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVnerd', '0007_movie_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('related_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TVnerd.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TVnerd.user')),
            ],
        ),
    ]
